SIMPLE_NODES = {
    "Quarry": {
        "type": "Raw Materials",
        "unlock": "-",
        "innate": "+500, **Natural**; Craft +1",
        "builds_into": ["Masonry"],
        "monument": False},
    "Salt Works": {
        "type": "Raw Materials",
        "unlock": "-",
        "innate": "+500, **Natural**; Craft +1",
        "builds_into": ["Smokehouse"],
        "monument": False},
    "Apiary": {
        "type": "Raw Materials",
        "unlock": "-",
        "innate": "+500, **Natural**; Craft +1",
        "builds_into": ["Chandlery", "Meadery"],
        "monument": False},
    "Peat Bog": {
        "type": "Raw Materials",
        "unlock": "-",
        "innate": "+500, **Natural**; Craft +1",
        "builds_into": ["Alchemy"],
        "monument": False},
    "Forestry": {
        "type": "Raw Materials",
        "unlock": "-",
        "innate": "+500, **Natural**; Craft +1",
        "builds_into": ["Carpentry", "Charcoal Burner", "Kiln"],
        "monument": False},
    "Fishmongery": {
        "type": "Raw Materials",
        "unlock": "-",
        "infrastructure_req": "Water Settlement",
        "innate": "+500, **Natural**; Craft +2",
        "builds_into": ["Harbor"],
        "monument": False},
    "Mine": {
        "type": "Raw Materials",
        "unlock": "-",
        "innate": "+500, **Natural**; Craft +1",
        "builds_into": ["Furnace","Siege Works"],
        "monument": False},
    "Arable Land": {
        "type": "Raw Materials",
        "unlock": "-",
        "innate": "+500, **Natural**; Craft +1",
        "builds_into": ["Herb Garden", "Animal Husbandry", "Granary", "Orchard","Vineyard"],
        "monument": False},
    "Common Land": {
        "type": "Raw Materials",
        "unlock": "-",
        "innate": "+1000, **Natural**, **Doubt +1**",
        "builds_into": ["Workyard", "Burgages"],
        "monument": False},
    "Herb Garden": {
        "type": "Husbandry",
        "unlock": "-",
        "innate": "+500, **Natural**; Craft +1",
        "efficient": "Arable Land",
        "builds_into": ["Spice Merchant"],
        "monument": False},
    "Animal Husbandry": {
        "type": "Husbandry",
        "unlock": "-",
        "innate": "**Natural**, Unlock **Crude** armor and shield. +500",
        "efficient": "Arable Land",
        "builds_into": ["Tannery", "Stable"],
        "monument": False},
    "Saddlery": {
        "type": "Husbandry",
        "unlock": "-",
        "innate": "+500, **Natural**; Speed +1; Unlocks Lance (Still requires Tier Unlock)",
        "efficient": ["Stable", "Caravanery"],
        "builds_into": [],
        "monument": False},
    "Vineyard": {
        "type": "Husbandry",
        "unlock": "-",
        "innate": "+500, **Natural**; +500 in **Fall**",
        "efficient": "Arable Land",
        "builds_into": ["Winery"],
        "monument": False},
    "Orchard": {
        "type": "Husbandry",
        "unlock": "-",
        "innate": "+800, **Natural**; +400 in **Fall**",
        "efficient": "Arable Land",
        "builds_into": ["Cidery"],
        "monument": False},
    "Carpentry": {
        "type": "Craft",
        "unlock": "-",
        "innate": "**Build Timer −1**; +300; Craft+1",
        "efficient": "Forestry",
        "builds_into": ["Fletchery", "Joinery", "Mill","Siege Works"],
        "monument": False},
    "Alchemy": {
        "type": "Craft",
        "unlock": "-",
        "innate": "+500; Craft+1",
        "efficient": "Peat Bog",
        "builds_into": ["Academy", "Apothecary", "Toxicarium"],
        "monument": False},
    "Masonry": {
        "type": "Craft",
        "unlock": "-",
        "innate": "**Build Timer −1**; Craft+1",
        "efficient": "Quarry",
        "builds_into": ["Courtyard", "Trade Guild", "Mill"],
        "monument": False},
    "Butchery": {
        "type": "Craft",
        "unlock": "-",
        "innate": "Natural; +500; **Upkeep -200**; Craft+1",
        "efficient": "Smokehouse",
        "builds_into": ["Levy Hall"],
        "monument": False},
    "Bakery": {
        "type": "Craft",
        "unlock": "-",
        "innate": "Natural; Faith +1; +500; Craft +2",
        "efficient": "Mill",
        "builds_into": ["Mill"],
        "monument": False},
    "Weavery": {
        "type": "Craft",
        "unlock": "-",
        "innate": "+1000; Craft +2",
        "efficient": "Merchant Quarter",
        "builds_into": ["Artisan Workshop", "Mill"],
        "monument": False},
    "Fletchery": {
        "type": "Craft",
        "unlock": "-",
        "innate": "Unlocks **Ranged Weapons**; **Upkeep -200**",
        "efficient": "Carpentry",
        "builds_into": ["Tiltyard"],
        "monument": False},
    "Chandlery": {
        "type": "Craft",
        "unlock": "-",
        "innate": "Craft +1; **Influence −1** to Cunning envoys targeting you",
        "efficient": "Apiary",
        "builds_into": ["Reliquary"],
        "monument": False},
    "Tannery": {
        "type": "Craft",
        "unlock": "-",
        "innate": "Natural; Unlocks **Cast** armor & shield. **Upkeep -200**; Craft +1",
        "efficient": "Animal Husbandry",
        "builds_into": ["Armory"],
        "monument": False},
    "Joinery": {
        "type": "Craft",
        "unlock": "Rising Industry",
        "innate": "unlocks **Shields**; **Upkeep -200**",
        "efficient": "Carpentry",
        "builds_into": [],
        "monument": False},
    "Furnace": {
        "type": "Craft",
        "unlock": "-",
        "innate": "Unlocks **Cast** Weapons; +500",
        "efficient": "Mine",
        "builds_into": ["Blacksmith"],
        "monument": False},
    "Blacksmith": {
        "type": "Craft",
        "unlock": "Rising Industry",
        "innate": "Craft +1; Unlocks **Wrought** Weapons",
        "efficient": "Furnace",
        "builds_into": ["Forge"],
        "monument": False},
    "Jewelry Foundry": {
        "type": "Craft",
        "unlock": "-",
        "innate": "+1300; **Influence +1** to Cunning envoys targeting this player; Craft +2",
        "efficient": "Gilded Foundry",
        "builds_into": [],
        "monument": False},
    "Armory": {
        "type": "Craft",
        "unlock": "Rising Industry",
        "innate": "Unlock **Wrought** armor & shield; **Upkeep -300**; Craft +1",
        "efficient": "Tannery",
        "builds_into": ["Gilded Foundry"],
        "monument": False},
    "Master Workshop": {
        "type": "Craft",
        "unlock": "Established Industry",
        "innate": "**Upkeep -200**; Craft +1; Add **Serrated** to Weapons",
        "efficient": "Forge",
        "builds_into": ["Advanced Blast Furnace"],
        "monument": False},
    "Gilded Foundry": {
        "type": "Craft",
        "unlock": "Established Industry",
        "innate": "Unlock **Forged** armor and shield. Craft +1.",
        "efficient": "Armory",
        "builds_into": ["Jewelry Foundry"],
        "monument": False},
    "Smokehouse": {
        "type": "Craft",
        "unlock": "-",
        "innate": "Natural; Craft +2; **Upkeep -500**",
        "efficient": ["Salt Works", "Charcoal Burner"],
        "builds_into": ["Butchery"],
        "monument": False},
    "Workyard": {
        "type": "Craft",
        "unlock": "—",
        "innate": "Natural; **Doubt +1**, +1000",
        "efficient": "Common Land",
        "builds_into": [],
        "monument": False},
    "Storehouse": {
        "type": "Craft",
        "unlock": "Sovereign Industry",
        "innate": "**Doubt +1**, +1200; **Build Timer −2**",
        "efficient": "Shipyard",
        "builds_into": [],
        "monument": False},
    "Meadery": {
        "type": "Craft",
        "unlock": "Established Industry",
        "innate": "Natural; **Faith +1**; **Speed +2** in **Winter**",
        "efficient": "Apiary",
        "builds_into": [],
        "monument": False},
    "Winery": {
        "type": "Craft",
        "unlock": "Established Industry",
        "innate": "Natural; +800; Craft +3",
        "efficient": "Vineyard",
        "builds_into": [],
        "monument": False},
    "Cidery": {
        "type": "Craft",
        "unlock": "Established Industry",
        "innate": "Natural; **Faith +1**; +800; Craft +1",
        "efficient": "Orchard",
        "builds_into": [],
        "monument": False},
    "Market Square": {
        "type": "Craft",
        "unlock": "Rising Industry",
        "innate": "Craft +2; +500",
        "efficient": "Courtyard",
        "builds_into": ["Inn", "Merchant Quarter", "Census Hall"],
        "monument": False},
    "Inn": {
        "type": "Craft",
        "unlock": "-",
        "innate": "**Faith +1** for trading partners with Craft 3+; **Faith +1**",
        "efficient": ["Market Square", "Merchant Quarter"],
        "builds_into": ["Courier Network", "Smuggler's Nook"],
        "monument": False},
    "Spice Merchant": {
        "type": "Craft",
        "unlock": "-",
        "innate": "Natural; +1000; Influence +1 to Cunning envoys targeting you; Craft +2",
        "efficient": "Herb Garden",
        "builds_into": [],
        "monument": False},
    "Harbor": {
        "type": "Craft",
        "unlock": "-",
        "infrastructure_req": "Water Settlement",
        "innate": "+500; Craft +2; **Extort 200** per **player** without **Harbor**",
        "efficient": "Fishmongery",
        "builds_into": ["Shipyard"],
        "monument": False},
    "Merchant Quarter": {
        "type": "Craft",
        "unlock": "Rising Industry",
        "innate": "+500; Trade Partners gain Craft +2",
        "efficient": "Market Square",
        "builds_into": ["Weavery", "Inn", "Money Lending"],
        "monument": False},
    "Money Lending": {
        "type": "Power",
        "unlock": "Established Industry",
        "innate": "**Extort 1000**; May loan money to Trade Partners at 100 per 1000/turn interest(minimum 100); on Default: Perform **Demand Tribute**",
        "efficient": "Merchant Quarter",
        "builds_into": [],
        "monument": False},
    "Census Hall": {
        "type": "Craft",
        "unlock": "-",
        "innate": "**Doubt +1**; +1000",
        "efficient": "Market Square",
        "builds_into": [],
        "monument": False},
    "Caravanery": {
        "type": "Craft",
        "unlock": "-",
        "innate": "Natural; **Influence -1** to **Intercept Caravan actions** targeting your **settlements**; **Craft +2**; **Speed -2** to non-allied players in your Province.",
        "efficient": "Stable",
        "builds_into": ["Saddlery", "Toll House"],
        "monument": False},
    "Stable": {
        "type": "Civic",
        "unlock": "1 Rising",
        "innate": "**Speed +2**, Natural; Unlocks Cavalry Spear (Still requires Tier Unlock)",
        "efficient": "Animal Husbandry",
        "builds_into": ["Saddlery", "Caravanery"],
        "monument": False},
    "Shipyard": {
        "type": "Craft",
        "unlock": "Established Industry",
        "infrastructure_req": "Water Settlement",
        "innate": "Craft +4; Water Territory treated as Grassland for movement",
        "efficient": "Harbor",
        "builds_into": ["Storehouse"],
        "monument": False},
    "Coliseum": {
        "type": "Civic",
        "unlock": "Rising Prowess",
        "innate": "**Faith +1** while at War; Unlocks **Man-at-Arms** for **Muster**",
        "efficient": "Conditioning Field",
        "builds_into": ["Grand Tournament"],
        "monument": False},
    "Interrogation Chambers": {
        "type": "Civic",
        "unlock": "Rising Piety",
        "innate": "Extort 500; Cunning actions targetting this player that cause Doubt are reduced by 1, to a minimum of 0.",
        "efficient": "Episcopal Court",
        "builds_into": ["Execution Dock"],
        "monument": False},
    "Abbey": {
        "type": "Civic",
        "unlock": "Established Piety",
        "innate": "Once/turn: **Influence +1** another player's Piety Envoy; Morale +1",
        "efficient": "Academy",
        "builds_into": ["Monastery"],
        "monument": False},
    "Reliquary": {
        "type": "Civic",
        "unlock": "Rising Piety",
        "infrastructure_req": "Cathedral",
        "innate": "+500; First **Doubt** per turn reduced by 1 (min 0)",
        "efficient": "Chandlery",
        "builds_into": ["Pilgrimage Site"],
        "monument": False},
    "Monastery": {
        "type": "Power",
        "unlock": "Established Piety",
        "innate": "**Influence −1** to Piety envoys targeting you; Other players can't Oppose your Piety Envoys",
        "efficient": "Abbey",
        "builds_into": ["Papal Palace", "Inquisitorial Palace"],
        "monument": False},
    "Bell Tower": {
        "type": "Civic",
        "unlock": "1 Established",
        "innate": "**+1 Influence**/turn; **Influence +1** to envoys sent during the Council Phase.",
        "efficient": "Jester's Court",
        "builds_into": [],
        "monument": False},
    "Execution Dock": {
        "type": "Civic",
        "unlock": "Established Piety",
        "innate": "**Influence -1** to **Foster Rebellion actions** targeting your **settlements**; **Players** who **target** you or your **settlements** with **actions** that cause **doubt** gain **Doubt +1**",
        "efficient": "Interrogation Chambers",
        "builds_into": [],
        "monument": False},
    "Hospitaller": {
        "type": "Power",
        "unlock": "Established Piety",
        "innate": "**Recover** improved by +1; Enduring: Successful Recovered rolls do not count towards the panic check threshold.",
        "efficient": "Infirmary",
        "builds_into": [],
        "monument": False},
    "Jester's Court": {
        "type": "Civic",
        "unlock": "1 Rising",
        "innate": "First and second **Oppose** on your Envoy each turn: reduce by 1",
        "efficient": "Courtyard",
        "builds_into": ["Bell Tower", "Embassy"],
        "monument": False},
    "Embassy": {
        "type": "Civic",
        "unlock": "1 Established",
        "innate": "**Influence +1** to Diplomacy Envoys; Whenever a player performs a Diplomacy Envoy targeting you, that envoy cannot be Opposed.",
        "efficient": "Jester's Court",
        "builds_into": ["Senate Hall"],
        "monument": False},
    "Granary": {
        "type": "Civic",
        "unlock": "Rising Industry",
        "innate": "Upkeep -500, Natural; Armies and Garrisons gain **Endurance** while Besieged",
        "efficient": "Arable Land",
        "builds_into": ["Supply Depot", "Citadel"],
        "monument": False},
    "Academy": {
        "type": "Civic",
        "unlock": "1 Rising",
        "infrastructure_req": "Library",
        "innate": "**Influence +1** to Council Envoys; **Influence +1** to non-Council Envoys",
        "efficient": "Alchemy",
        "builds_into": ["Abbey", "University", "Forgery Workshop", "War College"],
        "monument": False},
    "Courtyard": {
        "type": "Civic",
        "unlock": "-",
        "innate": "Craft +1; **Faith +1**",
        "efficient": "Masonry",
        "builds_into": ["Market Square", "Jester's Court", "Episcopal Court", "Conditioning Field"],
        "monument": False},
    "Episcopal Court": {
        "type": "Civic",
        "unlock": "Rising Piety",
        "innate": "**Faith +1**; Reduce the first instance of Doubt at start of turn by 1, min 0.",
        "efficient": "Courtyard",
        "builds_into": ["Interrogation Chambers"],
        "monument": False},
    "Conditioning Field": {
        "type": "Civic",
        "unlock": "Rising Prowess",
        "innate": "**Faith +1** while not at War; Armies gain **Nimble**",
        "efficient": "Courtyard",
        "builds_into": ["Coliseum"],
        "monument": False},
    "Grand Tournament": {
        "type": "Civic",
        "unlock": "Established Prowess",
        "innate": "**Faith +1**; Improve Parry by +1. 3x/turn: exchange 500 gold for **1 Influence**; Armies gain **Riposte**",
        "efficient": "Coliseum",
        "builds_into": [],
        "monument": False},
    "Apothecary": {
        "type": "Civic",
        "unlock": "-",
        "innate": f'+300; Gain Recover {RECOVER_BASE}, or improve Recover by +1.',
        "efficient": "Alchemy",
        "builds_into": ["Infirmary"],
        "monument": False},
    "Infirmary": {
        "type": "Civic",
        "unlock": "Rising Piety",
        "innate": "+500; Improve Recover by +1",
        "efficient": "Apothecary",
        "builds_into": ["Hospitaller"],
        "monument": False},
    "Supply Depot": {
        "type": "Civic",
        "unlock": "Rising Industry",
        "innate": "**Craft +2**; May **Muster** an Army in a Settlement under Siege and increment Muster Timers.",
        "efficient": "Granary",
        "builds_into": ["Citadel"],
        "monument": False},
    "Artisan Workshop": {
        "type": "Civic",
        "unlock": "Established Industry",
        "innate": "+1000, **Faith +1**",
        "efficient": "Weavery",
        "builds_into": ["Court Artists"],
        "monument": False},
    "University": {
        "type": "Power",
        "unlock": "1 Established",
        "innate": "May spend one additional **Influence** per Support or Oppose; +1 **Influence** per Domain you are Rising",
        "efficient": "Academy",
        "builds_into": ["Forgery Workshop", "Studium Generale"],
        "monument": False},
    "Trade Guild": {
        "type": "Civic",
        "unlock": "Rising Industry",
        "innate": "No Upkeep on **Primitive Infrastructure**; No Upkeep on **Developed Infrastructure**",
        "efficient": "Masonry",
        "builds_into": ["College of Engineering"],
        "monument": False},
    "Court Artists": {
        "type": "Civic",
        "unlock": "Established Industry",
        "innate": "**Extort 1000**; **Faith +1**; Targets of Extort from this Court Artist gain **Faith +1**",
        "efficient": "Artisan Workshop",
        "builds_into": ["Aristocratic Court"],
        "monument": False},
    "Courier Network": {
        "type": "Civic",
        "unlock": "-",
        "innate": "Once/turn: **Influence −1** on Target Envoy; Once/turn: successfully Performed Personal Envoy can be Performed next turn; send 1 fewer Envoys next turn",
        "efficient": "Inn",
        "builds_into": ["Smuggler's Nook"],
        "monument": False},
    "Toll House": {
        "type": "Civic",
        "unlock": "—",
        "innate": "Natural; Once/turn when an Army ends a Move action within Province: Perform a Diplomacy action targeting that army's player; **Extort 2000** when non-Allied Army ends a Move action within Province",
        "efficient": "Caravanery",
        "builds_into": ["Beacon Towers"],
        "monument": False},
    "College of Engineering": {
        "type": "Power",
        "unlock": "Established Industry",
        "innate": "No Upkeep on **Sophisticated Infrastructure**; **Build Timer −2**",
        "efficient": "Trade Guild",
        "builds_into": ["Office of Works"],
        "monument": False},
    "Secret Cellar": {
        "type": "Energy",
        "unlock": "Rising Cunning",
        "innate": "Natural; Failed Cunning envoys **Recoup 500 Gold**; Passed Cunning envoys **Recoup 500 Gold**",
        "efficient": ["Secrecy", "Thieves' Guild", "Outlaw Rookery", "Outrider Intercept Post"],
        "builds_into": ["Smuggler's Nook", "Black Market", "Forgery Workshop", "Forgotten Catacombs", "Thieves' Guild"],
        "monument": False},
    "Smuggler's Nook": {
        "type": "Secrecy",
        "unlock": "Established Cunning",
        "innate": "gain Immune Uprising (Bandit Camp Spawn at -5PO); Bandit Camps in your Outlaw Country don't target you and instead target other players randomly.",
        "efficient": ["Inn", "Courier Network", "Secret Cellar"],
        "builds_into": ["Black Market", "Outlaw Rookery"],
        "monument": False},
    "Black Market": {
        "type": "Secrecy",
        "unlock": "Established Cunning",
        "innate": "When another player **Extorts** gold from any source: **Extort 200** per 1000 (minimum 100) from that player at the end of that resolution. When another player **Recoups** gold from any source: **Extort 200** per 1000 (minimum 100) from that player at the end of that resolution.",
        "efficient": ["Smuggler's Nook", "Secret Cellar"],
        "builds_into": ["Thieves' Guild"],
        "monument": False},
    "Forgery Workshop": {
        "type": "Secrecy",
        "unlock": "Established Cunning",
        "innate": "**Extort 300** anytime a player Opposes an Envoy of yours; Once/turn: attempt another Cunning Envoy targeting a different player if your Cunning Envoy Failed",
        "efficient": ["Academy", "University", "Secret Cellar"],
        "builds_into": ["Cipher Chamber"],
        "monument": False},
    "Toxicarium": {
        "type": "Secrecy",
        "unlock": "Rising Cunning",
        "innate": "Weapons gain **Poison**; All Endorsed Cunning actions give an additional **Doubt +1** to Target",
        "efficient": ["Alchemy", "Forgotten Catacombs"],
        "builds_into": [],
        "monument": False},
    "Pilgrimage Site": {
        "type": "Energy",
        "unlock": "Established Piety",
        "innate": "Natural; **Extort 500** every player without a Pilgrimage Site; **Doubt +1** to all other players without a Pilgrimage Site",
        "efficient": "Reliquary",
        "builds_into": ["Preceptory of the Knight's Templar"],
        "monument": False},
    "Beacon Towers": {
        "type": "Energy",
        "unlock": "Rising Prowess",
        "innate": "Natural; Once per turn, you may select an Army within Province and move it up to its modified Speed. Whenever a non-allied Army ends a Move action within Province, you may immediately perform a Move action",
        "efficient": "Toll House",
        "builds_into": [],
        "monument": False},
    "Forgotten Catacombs": {
        "type": "Secrecy",
        "unlock": "Rising Cunning",
        "innate": "Whenever you are the target of **Extort**, reduce the Extort amount by 100. Cunning envoys against you can't be **Endorsed**",
        "efficient": "Secret Cellar",
        "builds_into": ["Toxicarium"],
        "monument": False},
    "Charcoal Burner": {
        "type": "Energy",
        "unlock": "Established Industry",
        "innate": "Natural; +500",
        "efficient": ["Forestry", "Kiln"],
        "builds_into": ["Smokehouse"],
        "monument": False},
    "Mill": {
        "type": "Energy",
        "unlock": "Rising Industry",
        "innate": "Natural; +500",
        "efficient": ["Bakery", "Weavery", "Forge", "Carpentry", "Masonry"],
        "builds_into": ["Bakery"],
        "monument": False},
    "Kiln": {
        "type": "Energy",
        "unlock": "Rising Industry",
        "innate": "Natural; +500",
        "efficient": "Forestry",
        "builds_into": ["Charcoal Burner"],
        "monument": False},
    "Burgages": {
        "type": "Energy",
        "unlock": "-",
        "innate": "+200, Natural; **Faith +1**",
        "efficient": "Common Land",
        "builds_into": [],
        "monument": False},
    "Levy Hall": {
        "type": "Power",
        "unlock": "Rising Prowess",
        "infrastructure_req": "Garrison",
        "innate": "Natural; **Upkeep -2000 while an army is range 0 of controlled settlement**",
        "efficient": "Butchery",
        "builds_into": [],
        "monument": False},
    "Siege Works": {
        "type": "Power",
        "unlock": "Rising Prowess",
        "innate": "**Siege Timer −2**; Sieges Increment in **Winter**",
        "efficient": ["Carpentry","Mine"],
        "builds_into": ["Siege Camp"],
        "monument": False},
    "Siege Camp": {
        "type": "Power",
        "unlock": "Established Prowess",
        "innate": "**Siege Timer −1**; Armies gain **Immune Strained** during Lay Siege",
        "efficient": "Siege Works",
        "builds_into": ["Artillery Park"],
        "monument": False},
    "Citadel": {
        "type": "Power",
        "unlock": "Established Industry",
        "innate": "**Siege Timer +3**, Controlled Settlements gain **Reach +1**",
        "efficient": ["Granary", "Supply Depot"],
        "builds_into": ["Imperial Palace"],
        "monument": False},
    "War College": {
        "type": "Power",
        "unlock": "Established Prowess",
        "innate": "Gain **+2 Influence** while At War; Unlocks **Sergeants** for Muster",
        "efficient": "Academy",
        "builds_into": ["Ministry of Military Strategy"],
        "monument": False},
    "Forge": {
        "type": "Power",
        "unlock": "Established Industry",
        "innate": "Craft +2; Unlocks **Forged** Tier Weapons",
        "efficient": "Blacksmith",
        "builds_into": ["Master Workshop", "Mill"],
        "monument": False},
    "Tiltyard": {
        "type": "Power",
        "unlock": "Established Prowess",
        "innate": "Armies may be equipped with a Ranged and a Melee Weapon simultaneously; In addition, armies may equip two of the same 1H Melee Weapon to gain **Dual Wield**.",
        "efficient": "Fletchery",
        "builds_into": ["Royal Pavilion"],
        "monument": False},
    "Court Armoury": {
        "type": "Power",
        "unlock": "Sovereign Industry",
        "innate": f"**{PLANISHING}**: Your to-Save can't be reduced beyond {CAP_THR}+. Upkeep -500; **Crafted** Armor & Shield Unlocked",
        "efficient": "Gilded Foundry",
        "builds_into": [],
        "monument": False},
    "Office of Works": {
        "type": "Monument",
        "unlock": "Sovereign Industry",
        "innate": "Settlements & allied armies inside them are not affected by 'Settlements being Besieged' restrictions. Siege Timer +2; Build Timer -2",
        "efficient": "College of Engineering",
        "builds_into": [],
        "monument": True},
    "Royal Pavilion": {
        "type": "Monument",
        "unlock": "Sovereign Prowess",
        "innate": "Armies gain **Immune Strained**, Improve Parry by +1; Gain +1 to Strike. Deadly, & Cleave also trigger Focused Strikes on a natural 8+.",
        "efficient": "Tiltyard",
        "builds_into": [],
        "monument": True},
    "Imperial Palace": {
        "type": "Monument",
        "unlock": "Established Prowess",
        "innate": "Each Empire Phase, all non-allied players with a lower Prowess value gain Doubt +2. If your Envoy would fail, it passes instead.",
        "efficient": "Citadel",
        "builds_into": [],
        "monument": True},
    "Artillery Park": {
        "type": "Monument",
        "unlock": "Sovereign Prowess",
        "innate": "Siege Timers ignore Wooden & Stone Walls. Unlocks Arquebus; Settlements you Siege can't Sally Forth. Siege Timer −1.",
        "efficient": "Siege Camp",
        "builds_into": [],
        "monument": True},
    "Ministry of Military Strategy": {
        "type": "Monument",
        "unlock": "Sovereign Prowess",
        "innate": "Always gains **Seize the Initiative**, and your opponent doesn't; max initiative is increased to 3; Gain Drilled.",
        "efficient": "War College",
        "builds_into": [],
        "monument": True},
    "Thieves' Guild": {
        "type": "Monument",
        "unlock": "Sovereign Cunning",
        "innate": "Whenever another player performs a Cunning action, you may recoup 1000 gold; **Extort 25%** of Trade Income from players who don't trade with you",
        "efficient": ["Black Market", "Secret Cellar"],
        "builds_into": ["Secret Cellar"],
        "monument": True},
    "Senate Hall": {
        "type": "Monument",
        "unlock": "1 Sovereign",
        "infrastructure_req": "Library + Town Hall",
        "innate": "**Faith +1**, gain **+1 Influence** per other player per Turn; Once/turn: Before players Support or Oppose, you may auto-**Condemn** an At War Envoy OR auto-**Endorse** an Ally's Envoy",
        "efficient": "Embassy",
        "builds_into": [],
        "monument": True},
    "Papal Palace": {
        "type": "Monument",
        "unlock": "Sovereign Piety",
        "innate": "You no longer pay cost for Piety Envoys. At the start of each turn, Tithe every other player with lower Piety, resolved in the Extort step.",
        "efficient": ["Monastery"],
        "builds_into": [],
        "monument": True},
    "Inquisitorial Palace": {
        "type": "Monument",
        "unlock": "Sovereign Piety",
        "innate": "**Doubt +1**; Unlocks **Grand Vizier** which uses your **Public Order** instead of your **Cunning** value. You may use your **Piety Value** as **Cunning Value** for **Grand Vizier**.",
        "efficient": "Monastery",
        "builds_into": [],
        "monument": True},
    "Preceptory of the Knight's Templar": {
        "type": "Monument",
        "unlock": "Sovereign Piety + Established Prowess",
        "innate": f"Armies gain **{CRUSADER}**: Automatically pass the first Panic Check of every Battle. Unlocks **Knight's Templar** for Muster",
        "efficient": "Pilgrimage Site",
        "builds_into": [],
        "monument": True},
    "Manor House": {
        "type": "Monument",
        "unlock": "Established Industry",
        "infrastructure_req": "Hamlet",
        "innate": "Natural; Gain +200 gold for each active natural specialization.",
        "efficient": "Natural",
        "builds_into": [],
        "monument": True},
    "Aristocratic Court": {
        "type": "Monument",
        "unlock": "Sovereign Cunning",
        "innate": "Each Empire Phase, Extort 500 from each non-allied player with a lower Cunning value. Your Vote counts as 2 votes toward Domain selection during the Council Phase.",
        "efficient": "Court Artists",
        "builds_into": [],
        "monument": True},
    "Studium Generale": {
        "type": "Monument",
        "unlock": "4 Established",
        "innate": "+1 **Influence** per **Established** Standing; May gain one **Sovereign Domain** effect without spending the Domain Points",
        "efficient": "University",
        "builds_into": [],
        "monument": True},
    "Outlaw Rookery": {
        "type": "Monument",
        "unlock": "Sovereign Cunning",
        "innate": "Both Bandit Camps & you have Influence +1 on Cunning actions. Endorsed Foster Rebellion places Bandit Camps with 25 retinues instead of 10.",
        "efficient": "Smuggler's Nook",
        "builds_into": ["Secret Cellar"],
        "monument": True},
    "Advanced Blast Furnace": {
        "type": "Monument",
        "unlock": "Sovereign Industry",
        "innate": "**Upkeep -500**; **Crafted** Weapons Unlocked; Craft +2",
        "efficient": "Master Workshop",
        "builds_into": [],
        "monument": True},
    "Cipher Chamber": {
        "type": "Secrecy",
        "unlock": "Established Cunning",
        "innate": "Once/turn when a player Sends an Envoy: that player must declare the specific Action & target they would Perform if the Envoy Passes (including sub-Actions). If it Passes, they must Perform that declared Action at the declared target. Once/turn: select any active **Timer** you did not select last turn; increase it by 2.",
        "efficient": "Forgery Workshop",
        "builds_into": ["Outrider Intercept Post"],
        "monument": False},
    "Outrider Intercept Post": {
        "type": "Monument",
        "unlock": "Sovereign Cunning",
        "innate": "Every Skirmish, you may force your opponent to reveal their Tactic Card they selected before you select your own.",
        "efficient": "Cipher Chamber",
        "builds_into": ["Secret Cellar"],
        "monument": True},
}